/**
 * @file shared.ts
 * @brief Shared scalar helpers for schema evaluation.
 */

import type {
    DiscriminatedUnionCase,
    LiteralValue,
    ObjectKeyLookup,
    Schema
} from "../schema/index.js";

const MAX_ARRAY_INDEX = 4_294_967_294;

/**
 * @brief Object shape accepted by object and record validators.
 * @details Values stay indexed by string keys only after the caller proves the
 * input is not null and not an array.
 */
export type UnknownRecord = Readonly<Record<string, unknown>>;

/**
 * @brief Descriptor subset safe for validation reads.
 * @details Only data descriptors are accepted because accessor descriptors can
 * execute user code and can return different values across reads.
 * @invariant Accessor descriptors never match this contract.
 */
export interface DataPropertyDescriptor {

    /**
     * @brief Captured property value.
     * @details The value remains unknown until a schema-specific validator consumes it.
     * @invariant Accessing this field does not execute user getter code.
     */
    readonly value: unknown;
}

/**
 * @brief Stable File metadata read from the host intrinsic getters.
 */
export interface FileInfo {
    readonly size: number;
    readonly type: string;
}

/**
 * @brief Check membership in an object schema key lookup.
 * @param keyLookup Null-prototype lookup generated by object schema construction.
 * @param key Candidate own key.
 * @returns True when the key belongs to the schema shape.
 * @details The lookup is used instead of `in` so prototype pollution cannot make
 * an undeclared key appear valid.
 */
export function hasObjectKey(keyLookup: ObjectKeyLookup, key: string): boolean {
    return Object.prototype.hasOwnProperty.call(keyLookup, key);
}

/**
 * @brief Read one own data property from a runtime object.
 * @details Reads one own property through its descriptor so getters are not executed.
 * @param record Plain object being validated.
 * @param key Own key to inspect.
 * @returns Own data descriptor, or undefined for missing/accessor properties.
 */
export function readOwnDataProperty(
    record: object,
    key: PropertyKey
): DataPropertyDescriptor | undefined {
    let descriptor: PropertyDescriptor | undefined;
    // eslint-disable-next-line no-restricted-syntax
    try {
        descriptor = Object.getOwnPropertyDescriptor(record, key);
    } catch {
        return undefined;
    }
    if (descriptor === undefined || !isDataPropertyDescriptor(descriptor)) {
        return undefined;
    }
    return descriptor;
}

/**
 * @brief Test for an own runtime property without leaking Proxy trap errors.
 * @param record Runtime object being validated.
 * @param key Own key to inspect.
 * @returns True/false when reflection succeeds, undefined when reflection traps.
 */
export function hasOwnRuntimeProperty(
    record: object,
    key: PropertyKey
): boolean | undefined {
    // eslint-disable-next-line no-restricted-syntax
    try {
        return Object.prototype.hasOwnProperty.call(record, key);
    } catch {
        return undefined;
    }
}

/**
 * @brief Read enumerable own string keys without leaking Proxy trap errors.
 */
export function readEnumerableStringKeys(value: object): readonly string[] | undefined {
    // eslint-disable-next-line no-restricted-syntax
    try {
        return Object.keys(value);
    } catch {
        return undefined;
    }
}

/**
 * @brief Read all own property keys without leaking Proxy trap errors.
 */
export function readOwnKeys(value: object): readonly PropertyKey[] | undefined {
    // eslint-disable-next-line no-restricted-syntax
    try {
        return Reflect.ownKeys(value);
    } catch {
        return undefined;
    }
}

/**
 * @brief Count own string-named properties without leaking Proxy trap errors.
 */
export function readOwnPropertyNameCount(value: object): number | undefined {
    // eslint-disable-next-line no-restricted-syntax
    try {
        return Object.getOwnPropertyNames(value).length;
    } catch {
        return undefined;
    }
}

/**
 * @brief Count own symbol-named properties without leaking Proxy trap errors.
 */
export function readOwnPropertySymbolCount(value: object): number | undefined {
    // eslint-disable-next-line no-restricted-syntax
    try {
        return Object.getOwnPropertySymbols(value).length;
    } catch {
        return undefined;
    }
}

/**
 * @brief Select a discriminated-union branch by its literal tag value.
 * @details The case list is already builder-validated for unique literals, so a
 * linear scan is enough for interpreter diagnostics while preserving declaration
 * order and avoiding a per-schema map allocation.
 * @param cases Closed discriminated union case list.
 * @param value Discriminant value read from input.
 * @returns Matching case schema, or undefined when the value is unknown.
 */
export function findDiscriminatedUnionCase(
    cases: readonly DiscriminatedUnionCase[],
    value: unknown
): Schema | undefined {
    for (let index = 0; index < cases.length; index += 1) {
        const unionCase = cases[index];
        if (unionCase !== undefined && Object.is(unionCase.literal, value)) {
            return unionCase.schema;
        }
    }
    return undefined;
}

/**
 * @brief Test for the only accepted refinement success value.
 * @param value Predicate return value.
 * @returns True only for the boolean literal true.
 */
export function isStrictTrue(value: unknown): boolean {
    return value === true;
}

/**
 * @brief Test whether a value can host object-schema properties.
 * @param value Candidate runtime value.
 * @returns True for non-array object values.
 */
export function isPlainRecord(value: unknown): value is UnknownRecord {
    if (typeof value !== "object" || value === null) {
        return false;
    }
    // eslint-disable-next-line no-restricted-syntax
    try {
        return !Array.isArray(value);
    } catch {
        return false;
    }
}

/**
 * Test mathematical divisibility without exposing binary floating-point
 * remainder noise such as `0.3 % 0.1`.
 */
export function isNumberMultipleOf(value: number, divisor: number): boolean {
    const ratio = value / divisor;
    const rounded = Math.round(ratio);
    const tolerance = Number.EPSILON * Math.max(Math.abs(ratio), 1);
    return Math.abs(ratio - rounded) < tolerance;
}

/**
 * @brief Test Array branding without leaking revoked-Proxy errors.
 */
export function isArrayValue(value: unknown): value is readonly unknown[] {
    // eslint-disable-next-line no-restricted-syntax
    try {
        return Array.isArray(value);
    } catch {
        return false;
    }
}

/**
 * @brief Test whether a descriptor carries a stable data slot.
 * @details Checks that a descriptor contains a data value instead of getter/setter code.
 * @param descriptor Descriptor returned by Object.getOwnPropertyDescriptor.
 * @returns True when the descriptor has a stable value slot.
 */
export function isDataPropertyDescriptor(
    descriptor: PropertyDescriptor
): descriptor is DataPropertyDescriptor {
    return Object.prototype.hasOwnProperty.call(descriptor, "value");
}

/**
 * @brief Test whether a property name is an in-bounds array index.
 * @details Array validation ignores non-index own properties exactly as indexed
 * loops do, but this helper lets sparse arrays avoid scanning every hole.
 * @param key Own property name returned from an array object.
 * @param length Current array length used as the upper bound.
 * @returns True for canonical own array-index names below the current length.
 * @invariant The result matches the indexes visited by a `0..length` loop.
 */
export function isArrayIndexKey(key: string, length: number): boolean {
    if (key.length === 0 || key === "length") {
        return false;
    }
    /*
     * Enumeration APIs expose array indexes as strings. Round-tripping through
     * Number rejects aliases such as "01", floats, negative keys, and length.
     */
    const index = Number(key);
    return Number.isInteger(index) &&
        index >= 0 &&
        index <= MAX_ARRAY_INDEX &&
        index < length &&
        String(index) === key;
}

/**
 * @brief Convert a runtime value into TypeSea's diagnostic type label.
 * @details JavaScript reports null as object and NaN as number. Diagnostics use
 * more precise labels so failure reports describe the actual value shape seen by
 * validators.
 * @param value Candidate runtime value.
 * @returns Stable diagnostic type label.
 */
export function actualType(value: unknown): string {
    if (value === null) {
        return "null";
    }
    // eslint-disable-next-line no-restricted-syntax
    try {
        if (Array.isArray(value)) {
            return "array";
        }
    } catch {
        return "object";
    }
    if (isValidDateObject(value)) {
        return "date";
    }
    if (readFileInfo(value) !== undefined) {
        return "file";
    }
    if (readMapEntries(value) !== undefined) {
        return "map";
    }
    if (readSetValues(value) !== undefined) {
        return "set";
    }
    if (typeof value === "bigint") {
        return "bigint";
    }
    if (typeof value === "symbol") {
        return "symbol";
    }
    if (typeof value === "number" && Number.isNaN(value)) {
        return "nan";
    }
    return typeof value;
}

/**
 * @brief Probe whether host reflection can inspect a candidate input.
 * @param value Candidate runtime value.
 * @returns True when ordinary reflection succeeds without executing getters.
 * @details Compiled validators use this only after generated code throws. A
 * false result means the input itself is hostile, such as a revoked Proxy or a
 * Proxy whose reflection traps throw. A true result lets schema and API misuse
 * errors keep surfacing as programmer-facing exceptions.
 */
export function isInspectableValue(value: unknown): boolean {
    if (typeof value !== "object" || value === null) {
        return true;
    }
    // eslint-disable-next-line no-restricted-syntax
    try {
        Array.isArray(value);
        Object.getPrototypeOf(value);
        const keys = Reflect.ownKeys(value);
        if (keys.length !== 0) {
            const key = keys[0];
            if (key !== undefined) {
                Object.getOwnPropertyDescriptor(value, key);
            }
        }
        return true;
    } catch {
        return false;
    }
}

/**
 * @brief Validate a Date object without reading user-overridable methods.
 * @param value Candidate runtime value.
 * @returns True when value is a Date with a finite time value.
 */
export function isValidDateObject(value: unknown): value is Date {
    // eslint-disable-next-line no-restricted-syntax
    try {
        return Number.isFinite(Date.prototype.getTime.call(value));
    } catch {
        return false;
    }
}

/**
 * @brief Read a Date object's time value through the intrinsic method.
 * @param value Date object already accepted by isValidDateObject.
 * @returns Epoch millisecond value.
 */
export function readDateTime(value: Date): number {
    return Date.prototype.getTime.call(value);
}

/**
 * @brief Read a Map iterator only after proving the internal Map slot exists.
 * @param value Candidate runtime value.
 * @returns Intrinsic entries iterator, or undefined for forged Map prototypes.
 * @details Calling the intrinsic proves the internal Map slot while turning
 * forged prototypes and hostile proxies into ordinary validation failure.
 */
export function readMapEntries(
    value: unknown
): IterableIterator<[unknown, unknown]> | undefined {
    // eslint-disable-next-line no-restricted-syntax
    try {
        return Map.prototype.entries.call(value) as IterableIterator<[unknown, unknown]>;
    } catch {
        return undefined;
    }
}

/**
 * @brief Read Map size without invoking user-owned accessors.
 * @param value Candidate runtime value.
 * @returns Map size, or undefined when the value is not a valid Map.
 * @details The helper reuses the intrinsic entries reader so forged Map
 * prototypes fail closed without adding another exception boundary.
 */
export function readMapSize(value: unknown): number | undefined {
    const iterator = readMapEntries(value);
    if (iterator === undefined) {
        return undefined;
    }
    let size = 0;
    for (;;) {
        const step = iterator.next();
        if (step.done === true) {
            return size;
        }
        size += 1;
    }
}

/**
 * @brief Read a Set iterator only after proving the internal Set slot exists.
 * @param value Candidate runtime value.
 * @returns Intrinsic values iterator, or undefined for forged Set prototypes.
 */
export function readSetValues(value: unknown): IterableIterator<unknown> | undefined {
    // eslint-disable-next-line no-restricted-syntax
    try {
        return Set.prototype.values.call(value) as IterableIterator<unknown>;
    } catch {
        return undefined;
    }
}

/**
 * @brief Read Set size through the intrinsic getter.
 * @param value Candidate runtime value with an internal Set slot.
 * @returns Set size, or undefined if the intrinsic getter rejects the receiver.
 */
export function readSetSize(value: unknown): number | undefined {
    // eslint-disable-next-line no-restricted-syntax
    try {
        const size: unknown = Reflect.get(Set.prototype, "size", value);
        return typeof size === "number" ? size : undefined;
    } catch {
        return undefined;
    }
}

/**
 * @brief Read File size and MIME type through the host File intrinsic getters.
 * @param value Candidate runtime value.
 * @returns Stable file metadata, or undefined when File is unavailable or forged.
 * @details The helper never relies on module-load availability of File. It also
 * avoids calling user-owned getters on plain objects that merely imitate File.
 */
export function readFileInfo(value: unknown): FileInfo | undefined {
    const constructor: unknown = globalThis.File;
    if (typeof constructor !== "function" ||
        !ordinaryHasInstance(value, constructor)) {
        return undefined;
    }
    const prototype = readConstructorPrototype(constructor);
    if (prototype === undefined) {
        return undefined;
    }
    // eslint-disable-next-line no-restricted-syntax
    try {
        const size: unknown = Reflect.get(prototype, "size", value);
        const type: unknown = Reflect.get(prototype, "type", value);
        if (typeof size !== "number" ||
            !Number.isFinite(size) ||
            size < 0 ||
            typeof type !== "string") {
            return undefined;
        }
        return {
            size,
            type: type.toLowerCase()
        };
    } catch {
        return undefined;
    }
}

/**
 * @brief Read constructor prototype metadata without dynamic typing.
 */
function readConstructorPrototype(value: object): object | undefined {
    const descriptor = Object.getOwnPropertyDescriptor(value, "prototype");
    const prototype: unknown = descriptor?.value;
    if (descriptor === undefined ||
        !Object.prototype.hasOwnProperty.call(descriptor, "value") ||
        typeof prototype !== "object" ||
        prototype === null) {
        return undefined;
    }
    return prototype;
}

/**
 * @brief Execute ordinary instanceof without invoking custom hasInstance hooks.
 * @param value Candidate runtime value.
 * @param constructor Constructor function stored in the schema.
 * @returns True when the ordinary prototype-chain check accepts the value.
 */
export function ordinaryHasInstance(
    value: unknown,
    constructor: object
): boolean {
    // eslint-disable-next-line no-restricted-syntax
    try {
        return Function.prototype[Symbol.hasInstance].call(constructor, value);
    } catch {
        return false;
    }
}

/**
 * @brief Render a literal schema value for the `expected` diagnostic field.
 * @details String values are JSON-quoted and negative zero is preserved because
 * both cases are otherwise easy to misread in generated messages.
 * @param value Literal value from a schema.
 * @returns Stable expected-value label for diagnostics.
 */
export function literalToExpected(value: LiteralValue): string {
    if (value === null) {
        return "null";
    }
    if (value === undefined) {
        return "undefined";
    }
    if (typeof value === "string") {
        return JSON.stringify(value);
    }
    if (typeof value === "number" && Object.is(value, -0)) {
        return "-0";
    }
    if (typeof value === "symbol") {
        return String(value);
    }
    return String(value);
}
