/**
 * @file shared.ts
 * @brief Shared scalar helpers for schema evaluation.
 * @details Interpreter helpers keep safe descriptor-based reads and diagnostic collection
 * aligned with compiled behavior.
 */

import type {
    DiscriminatedUnionCase,
    LiteralValue,
    ObjectKeyLookup,
    Schema
} from "../schema/index.js";

const MAX_ARRAY_INDEX = 4_294_967_294;

/**
 * @brief Object shape accepted by object and record validators.
 * @details Values stay indexed by string keys only after the caller proves the
 * input is not null and not an array.
 */
export type UnknownRecord = Readonly<Record<string, unknown>>;

/**
 * @brief Descriptor subset safe for validation reads.
 * @details Only data descriptors are accepted because accessor descriptors can
 * execute user code and can return different values across reads.
 * @invariant Accessor descriptors never match this contract.
 */
export interface DataPropertyDescriptor {

    /**
     * @brief Captured property value.
     * @details The value remains unknown until a schema-specific validator consumes it.
     * @invariant Accessing this field does not execute user getter code.
     */
    readonly value: unknown;
}

/**
 * @brief Check membership in an object schema key lookup.
 * @param keyLookup Null-prototype lookup generated by object schema construction.
 * @param key Candidate own key.
 * @returns True when the key belongs to the schema shape.
 * @details The lookup is used instead of `in` so prototype pollution cannot make
 * an undeclared key appear valid.
 */
export function hasObjectKey(keyLookup: ObjectKeyLookup, key: string): boolean {
    return Object.prototype.hasOwnProperty.call(keyLookup, key);
}

/**
 * @brief Read one own data property from a runtime object.
 * @details Reads one own property through its descriptor so getters are not executed.
 * @param record Plain object being validated.
 * @param key Own key to inspect.
 * @returns Own data descriptor, or undefined for missing/accessor properties.
 */
export function readOwnDataProperty(
    record: UnknownRecord,
    key: string
): DataPropertyDescriptor | undefined {
    const descriptor = Object.getOwnPropertyDescriptor(record, key);
    if (descriptor === undefined || !isDataPropertyDescriptor(descriptor)) {
        return undefined;
    }
    return descriptor;
}

/**
 * @brief Select a discriminated-union branch by its literal tag value.
 * @details The case list is already builder-validated for unique literals, so a
 * linear scan is enough for interpreter diagnostics while preserving declaration
 * order and avoiding a per-schema map allocation.
 * @param cases Closed discriminated union case list.
 * @param value Discriminant string read from input.
 * @returns Matching case schema, or undefined when the value is unknown.
 */
export function findDiscriminatedUnionCase(
    cases: readonly DiscriminatedUnionCase[],
    value: string
): Schema | undefined {
    for (let index = 0; index < cases.length; index += 1) {
        const unionCase = cases[index];
        if (unionCase !== undefined && Object.is(unionCase.literal, value)) {
            return unionCase.schema;
        }
    }
    return undefined;
}

/**
 * @brief Test for the only accepted refinement success value.
 * @details Interpreter helpers keep safe descriptor-based reads and diagnostic collection
 * aligned with compiled behavior.
 * @param value Predicate return value.
 * @returns True only for the boolean literal true.
 */
export function isStrictTrue(value: unknown): boolean {
    return value === true;
}

/**
 * @brief Test whether a value can host object-schema properties.
 * @details Interpreter helpers keep safe descriptor-based reads and diagnostic collection
 * aligned with compiled behavior.
 * @param value Candidate runtime value.
 * @returns True for non-array object values.
 */
export function isPlainRecord(value: unknown): value is UnknownRecord {
    return typeof value === "object" && value !== null && !Array.isArray(value);
}

/**
 * @brief Test whether a descriptor carries a stable data slot.
 * @details Checks that a descriptor contains a data value instead of getter/setter code.
 * @param descriptor Descriptor returned by Object.getOwnPropertyDescriptor.
 * @returns True when the descriptor has a stable value slot.
 */
export function isDataPropertyDescriptor(
    descriptor: PropertyDescriptor
): descriptor is DataPropertyDescriptor {
    return Object.prototype.hasOwnProperty.call(descriptor, "value");
}

/**
 * @brief Test whether a property name is an in-bounds array index.
 * @details Array validation ignores non-index own properties exactly as indexed
 * loops do, but this helper lets sparse arrays avoid scanning every hole.
 * @param key Own property name returned from an array object.
 * @param length Current array length used as the upper bound.
 * @returns True for canonical own array-index names below the current length.
 * @invariant The result matches the indexes visited by a `0..length` loop.
 */
export function isArrayIndexKey(key: string, length: number): boolean {
    if (key.length === 0 || key === "length") {
        return false;
    }
    /*
     * Enumeration APIs expose array indexes as strings. Round-tripping through
     * Number rejects aliases such as "01", floats, negative keys, and length.
     */
    const index = Number(key);
    return Number.isInteger(index) &&
        index >= 0 &&
        index <= MAX_ARRAY_INDEX &&
        index < length &&
        String(index) === key;
}

/**
 * @brief Convert a runtime value into TypeSea's diagnostic type label.
 * @details JavaScript reports null as object and NaN as number. Diagnostics use
 * more precise labels so failure reports describe the actual value shape seen by
 * validators.
 * @param value Candidate runtime value.
 * @returns Stable diagnostic type label.
 */
export function actualType(value: unknown): string {
    if (value === null) {
        return "null";
    }
    if (Array.isArray(value)) {
        return "array";
    }
    if (typeof value === "bigint") {
        return "bigint";
    }
    if (typeof value === "symbol") {
        return "symbol";
    }
    if (typeof value === "number" && Number.isNaN(value)) {
        return "nan";
    }
    return typeof value;
}

/**
 * @brief Render a literal schema value for the `expected` diagnostic field.
 * @details String values are JSON-quoted and negative zero is preserved because
 * both cases are otherwise easy to misread in generated messages.
 * @param value Literal value from a schema.
 * @returns Stable expected-value label for diagnostics.
 */
export function literalToExpected(value: LiteralValue): string {
    if (value === null) {
        return "null";
    }
    if (value === undefined) {
        return "undefined";
    }
    if (typeof value === "string") {
        return JSON.stringify(value);
    }
    if (typeof value === "number" && Object.is(value, -0)) {
        return "-0";
    }
    if (typeof value === "symbol") {
        return String(value);
    }
    return String(value);
}
