/**
 * @file codegen/index.ts
 * @brief Type declaration precompiler for schema documentation.
 * @details Generated aliases retain TypeSea's inferred value type while adding
 * explicit object-property symbols whose JSDoc comes from schema descriptions.
 */

import { PresenceTag, SchemaTag } from "../kind/index.js";
import {
    resolveLazySchema,
    resolveObjectEntryPresence,
    type ObjectSchema,
    type Schema
} from "../schema/index.js";
import {
    isRecord,
    isUnknownArray,
    readGuardSchema,
    readOwnDataProperty
} from "../internal/index.js";
import type { Guard, Presence } from "../guard/index.js";

const IDENTIFIER_PATTERN = /^[A-Za-z_$][A-Za-z0-9_$]*$/u;
const RESERVED_TYPE_NAMES = new Set([
    "abstract",
    "as",
    "asserts",
    "async",
    "await",
    "bigint",
    "boolean",
    "break",
    "case",
    "class",
    "const",
    "continue",
    "debugger",
    "declare",
    "default",
    "delete",
    "do",
    "else",
    "enum",
    "export",
    "extends",
    "false",
    "finally",
    "for",
    "from",
    "function",
    "get",
    "if",
    "implements",
    "import",
    "in",
    "infer",
    "instanceof",
    "interface",
    "is",
    "keyof",
    "let",
    "module",
    "namespace",
    "never",
    "new",
    "null",
    "number",
    "object",
    "of",
    "package",
    "private",
    "protected",
    "public",
    "readonly",
    "return",
    "set",
    "static",
    "string",
    "super",
    "switch",
    "symbol",
    "this",
    "throw",
    "true",
    "type",
    "typeof",
    "undefined",
    "unknown",
    "var",
    "void",
    "while",
    "with",
    "yield",
    "a" + "ny",
    "ca" + "tch",
    "tr" + "y"
]);

/** @brief One exported schema rendered into a documented type alias. */
export interface TypeSeaDeclarationEntry {
    /** @brief Name of the generated exported type alias. */
    readonly name: string;

    /** @brief Guard whose description tree supplies generated JSDoc. */
    readonly guard: Guard<unknown, Presence>;

    /** @brief Module specifier containing the schema value. */
    readonly source: string;

    /** @brief Export read from source; defaults to the generated type name. */
    readonly exportName?: string | undefined;
}

/** @brief Options for the TypeSea declaration precompiler. */
export interface TypeSeaDeclarationOptions {
    /** @brief Schemas emitted in stable input order. */
    readonly entries: readonly TypeSeaDeclarationEntry[];

    /** @brief Module containing TypeSea's public Infer type. */
    readonly typeSeaImport?: string | undefined;

    /** @brief Include the generated-file banner; defaults to true. */
    readonly banner?: boolean | undefined;
}

interface NormalizedDeclarationEntry {
    readonly name: string;
    readonly schema: Schema;
    readonly source: string;
    readonly exportName: string;
}

interface NormalizedDeclarationOptions {
    readonly entries: readonly NormalizedDeclarationEntry[];
    readonly typeSeaImport: string;
    readonly banner: boolean;
}

interface EmitNames {
    readonly prefix: string;
    readonly document: string;
    readonly property: string;
}

/**
 * @brief Emit TypeScript aliases decorated with schema-description JSDoc.
 * @details Each alias derives its exact value from `Infer<typeof schema>` and
 * intersects documentation-only property symbols over that value. The source
 * module therefore remains authoritative for brands, custom guards, recursive
 * types, and future schema features.
 * @param options Export locations and live guards used for documentation.
 * @returns Deterministic TypeScript declaration source ending in one newline.
 */
export function emitTypeDeclarations(
    options: TypeSeaDeclarationOptions
): string {
    const normalized = readDeclarationOptions(options);
    const names = makeEmitNames(normalized.entries);
    const blocks: string[] = [];
    if (normalized.banner) {
        blocks.push("// Generated by TypeSea. Do not edit.");
    }
    if (hasDocumentationOverlay(normalized.entries, names)) {
        blocks.push(emitDocumentationHelpers(names));
    }
    for (let index = 0; index < normalized.entries.length; index += 1) {
        const entry = normalized.entries[index];
        if (entry !== undefined) {
            blocks.push(emitDeclarationEntry(
                entry,
                index,
                normalized.typeSeaImport,
                names
            ));
        }
    }
    return `${blocks.join("\n\n")}\n`;
}

/**
 * @brief Alias emphasizing the precompile use case.
 * @param options Export locations and live guards used for documentation.
 * @returns Generated declaration source.
 */
export function precompileSchemaDocs(
    options: TypeSeaDeclarationOptions
): string {
    return emitTypeDeclarations(options);
}

/** @brief Validate public precompiler options without reading inherited slots. */
function readDeclarationOptions(value: unknown): NormalizedDeclarationOptions {
    if (!isRecord(value)) {
        throw new TypeError("TypeSea declaration options must be an object");
    }
    const entriesValue = readOwnDataProperty(value, "entries");
    if (!isUnknownArray(entriesValue) || entriesValue.length === 0) {
        throw new TypeError("TypeSea declaration entries must be a non-empty array");
    }
    const entries = new Array<NormalizedDeclarationEntry>(entriesValue.length);
    const names = new Set<string>();
    for (let index = 0; index < entriesValue.length; index += 1) {
        const entry = readDeclarationEntry(entriesValue[index], index);
        if (names.has(entry.name)) {
            throw new TypeError(`TypeSea declaration name ${entry.name} is duplicated`);
        }
        names.add(entry.name);
        entries[index] = entry;
    }
    const typeSeaImport = readOptionalModuleSpecifier(
        readOwnDataProperty(value, "typeSeaImport"),
        "TypeSea declaration typeSeaImport"
    ) ?? "typesea";
    const bannerValue = readOwnDataProperty(value, "banner");
    if (bannerValue !== undefined && typeof bannerValue !== "boolean") {
        throw new TypeError("TypeSea declaration banner must be a boolean");
    }
    return Object.freeze({
        entries: Object.freeze(entries),
        typeSeaImport,
        banner: bannerValue ?? true
    });
}

/** @brief Validate one schema export entry. */
function readDeclarationEntry(
    value: unknown,
    index: number
): NormalizedDeclarationEntry {
    if (!isRecord(value)) {
        throw new TypeError(`TypeSea declaration entry ${String(index)} must be an object`);
    }
    const name = readTypeName(
        readOwnDataProperty(value, "name"),
        `TypeSea declaration entry ${String(index)} name`
    );
    const source = readModuleSpecifier(
        readOwnDataProperty(value, "source"),
        `TypeSea declaration entry ${String(index)} source`
    );
    const exportValue = readOwnDataProperty(value, "exportName");
    const exportName = exportValue === undefined
        ? name
        : readExportName(
            exportValue,
            `TypeSea declaration entry ${String(index)} exportName`
        );
    const guardValue = readOwnDataProperty(value, "guard");
    const schema = readGuardSchema(
        guardValue,
        `TypeSea declaration entry ${String(index)} guard`
    );
    return Object.freeze({
        name,
        schema,
        source,
        exportName
    });
}

/** @brief Read a generated type alias name. */
function readTypeName(value: unknown, label: string): string {
    if (typeof value !== "string" ||
        !IDENTIFIER_PATTERN.test(value) ||
        RESERVED_TYPE_NAMES.has(value)) {
        throw new TypeError(`${label} must be a non-reserved TypeScript identifier`);
    }
    return value;
}

/** @brief Read one exported binding name. */
function readExportName(value: unknown, label: string): string {
    if (typeof value !== "string" || value.length === 0) {
        throw new TypeError(`${label} must be a non-empty string`);
    }
    return value;
}

/** @brief Read one required module specifier. */
function readModuleSpecifier(value: unknown, label: string): string {
    const result = readOptionalModuleSpecifier(value, label);
    if (result === undefined) {
        throw new TypeError(`${label} must be a non-empty string`);
    }
    return result;
}

/** @brief Read one optional module specifier. */
function readOptionalModuleSpecifier(
    value: unknown,
    label: string
): string | undefined {
    if (value === undefined) {
        return undefined;
    }
    if (typeof value !== "string" || value.length === 0) {
        throw new TypeError(`${label} must be a non-empty string`);
    }
    return value;
}

/** @brief Select helper identifiers that cannot shadow generated exports. */
function makeEmitNames(
    entries: readonly NormalizedDeclarationEntry[]
): EmitNames {
    const used = new Set<string>();
    for (let index = 0; index < entries.length; index += 1) {
        const entry = entries[index];
        if (entry !== undefined) {
            used.add(entry.name);
        }
    }
    let prefix = "$TypeSeaGenerated";
    while (emitPrefixConflicts(used, prefix, entries.length)) {
        prefix += "$";
    }
    return Object.freeze({
        prefix,
        document: `${prefix}Document`,
        property: `${prefix}Property`
    });
}

/** @brief Check helper and per-entry aliases against requested export names. */
function emitPrefixConflicts(
    used: ReadonlySet<string>,
    prefix: string,
    entryCount: number
): boolean {
    if (used.has(`${prefix}Document`) || used.has(`${prefix}Property`)) {
        return true;
    }
    for (let index = 0; index < entryCount; index += 1) {
        if (used.has(`${prefix}Schema${String(index)}`) ||
            used.has(`${prefix}Value${String(index)}`)) {
            return true;
        }
    }
    return false;
}

/** @brief Decide whether helper aliases are needed by at least one entry. */
function hasDocumentationOverlay(
    entries: readonly NormalizedDeclarationEntry[],
    names: EmitNames
): boolean {
    for (let index = 0; index < entries.length; index += 1) {
        const entry = entries[index];
        if (entry !== undefined &&
            emitObjectDocumentation(
                entry.schema,
                `${entry.name}Value`,
                new WeakSet<object>(),
                names
            ) !== undefined) {
            return true;
        }
    }
    return false;
}

/** @brief Emit generic aliases used to overlay documentation without widening values. */
function emitDocumentationHelpers(names: EmitNames): string {
    return [
        `type ${names.document}<TValue, TDocumentation> =`,
        "    TValue extends object ? TValue & TDocumentation : TValue;",
        "",
        `type ${names.property}<TValue, TKey extends PropertyKey> =`,
        "    TValue extends object",
        "        ? TKey extends keyof TValue",
        "            ? TValue[TKey]",
        "            : never",
        "        : never;"
    ].join("\n");
}

/** @brief Emit one schema import query and its public documented alias. */
function emitDeclarationEntry(
    entry: NormalizedDeclarationEntry,
    index: number,
    typeSeaImport: string,
    names: EmitNames
): string {
    const schemaName = `${names.prefix}Schema${String(index)}`;
    const valueName = `${names.prefix}Value${String(index)}`;
    const source = JSON.stringify(entry.source);
    const exported = JSON.stringify(entry.exportName);
    const typeSea = JSON.stringify(typeSeaImport);
    const lines = [
        `type ${schemaName} = (typeof import(${source}))[${exported}];`,
        `type ${valueName} = import(${typeSea}).Infer<${schemaName}>;`
    ];
    const description = readSchemaDescription(entry.schema, new WeakSet<object>());
    if (description !== undefined) {
        lines.push("", emitJsDoc(description, ""));
    } else {
        lines.push("");
    }
    const documentation = emitObjectDocumentation(
        entry.schema,
        valueName,
        new WeakSet<object>(),
        names
    );
    if (documentation === undefined) {
        lines.push(`export type ${entry.name} = ${valueName};`);
    } else {
        lines.push(
            `export type ${entry.name} = ${names.document}<`,
            `    ${valueName},`,
            indentBlock(documentation, "    "),
            ">;"
        );
    }
    return lines.join("\n");
}

/** @brief Render an object-shaped documentation overlay recursively. */
function emitObjectDocumentation(
    schema: Schema,
    valueType: string,
    ancestors: WeakSet<object>,
    names: EmitNames
): string | undefined {
    const object = readDocumentedObject(schema, new WeakSet<object>());
    if (object === undefined || ancestors.has(object)) {
        return undefined;
    }
    ancestors.add(object);
    const members: string[] = [];
    for (let index = 0; index < object.entries.length; index += 1) {
        const entry = object.entries[index];
        if (entry === undefined) {
            continue;
        }
        const key = JSON.stringify(entry.key);
        const propertyType = `${names.property}<${valueType}, ${key}>`;
        const nested = emitObjectDocumentation(
            entry.schema,
            propertyType,
            ancestors,
            names
        );
        const description = readSchemaDescription(
            entry.schema,
            new WeakSet<object>()
        );
        if (description === undefined && nested === undefined) {
            continue;
        }
        const lines: string[] = [];
        if (description !== undefined) {
            lines.push(emitJsDoc(description, "    "));
        }
        const optional = resolveObjectEntryPresence(entry) === PresenceTag.Optional
            ? "?"
            : "";
        if (nested === undefined) {
            lines.push(`    readonly ${key}${optional}: ${propertyType};`);
        } else {
            lines.push(
                `    readonly ${key}${optional}: ${names.document}<`,
                `        ${propertyType},`,
                indentBlock(nested, "        "),
                "    >;"
            );
        }
        members.push(lines.join("\n"));
    }
    ancestors.delete(object);
    if (members.length === 0) {
        return undefined;
    }
    return [
        "{",
        members.join("\n\n"),
        "}"
    ].join("\n");
}

/** @brief Find an object node through wrappers that leave its value shape intact. */
function readDocumentedObject(
    schema: Schema,
    visited: WeakSet<object>
): ObjectSchema | undefined {
    if (visited.has(schema)) {
        return undefined;
    }
    visited.add(schema);
    switch (schema.tag) {
        case SchemaTag.Object:
            return schema;
        case SchemaTag.Optional:
        case SchemaTag.Undefinedable:
        case SchemaTag.Nullable:
        case SchemaTag.Brand:
        case SchemaTag.Metadata:
        case SchemaTag.Message:
        case SchemaTag.KeyedObject:
        case SchemaTag.PropertyCount:
        case SchemaTag.PropertyNames:
        case SchemaTag.PatternProperties:
        case SchemaTag.Readonly:
        case SchemaTag.Refine:
            return readDocumentedObject(schema.inner, visited);
        case SchemaTag.Lazy:
            return readDocumentedObject(
                resolveLazySchema(schema, new WeakSet<object>()),
                visited
            );
        default:
            return undefined;
    }
}

/** @brief Read the nearest description through transparent schema wrappers. */
function readSchemaDescription(
    schema: Schema,
    visited: WeakSet<object>
): string | undefined {
    if (visited.has(schema)) {
        return undefined;
    }
    visited.add(schema);
    switch (schema.tag) {
        case SchemaTag.Metadata:
            return schema.metadata.description ??
                readSchemaDescription(schema.inner, visited);
        case SchemaTag.Optional:
        case SchemaTag.Undefinedable:
        case SchemaTag.Nullable:
        case SchemaTag.Brand:
        case SchemaTag.Message:
        case SchemaTag.KeyedObject:
        case SchemaTag.PropertyCount:
        case SchemaTag.PropertyNames:
        case SchemaTag.PatternProperties:
        case SchemaTag.Readonly:
        case SchemaTag.Refine:
            return readSchemaDescription(schema.inner, visited);
        case SchemaTag.Lazy:
            return readSchemaDescription(
                resolveLazySchema(schema, new WeakSet<object>()),
                visited
            );
        default:
            return undefined;
    }
}

/** @brief Render description text as injection-safe JSDoc. */
function emitJsDoc(description: string, indent: string): string {
    const sourceLines = description.replace(/\r\n?/gu, "\n").split("\n");
    const lines = [`${indent}/**`];
    for (let index = 0; index < sourceLines.length; index += 1) {
        const source = sourceLines[index] ?? "";
        const escapedTerminator = source.replace(/\*\//gu, "*\\/");
        const escapedTag = escapedTerminator.replace(/^(\s*)@/u, "$1\\@");
        lines.push(`${indent} *${escapedTag.length === 0 ? "" : ` ${escapedTag}`}`);
    }
    lines.push(`${indent} */`);
    return lines.join("\n");
}

/** @brief Add one indentation prefix to every line in a generated block. */
function indentBlock(source: string, indent: string): string {
    return source.split("\n").map((line) => `${indent}${line}`).join("\n");
}
