/**
 * @file index.ts
 * @brief Public builder module aggregation.
 * @details This barrel keeps public import paths stable while implementation files remain
 * split by responsibility.
 */

export {
    array,
    discriminatedUnion,
    intersect,
    looseRecord,
    map,
    partialRecord,
    record,
    set,
    templateLiteral,
    tuple,
    union,
    xor,
    type TemplateLiteralPart
} from "./composite.js";
export {
    check,
    custom,
    lazy,
    exactOptional,
    describe,
    example,
    meta,
    message,
    metadata,
    nonoptional,
    nullable,
    nullish,
    optional,
    readonly,
    refine,
    superRefine,
    title,
    unwrap,
    undefinedable
} from "./modifier.js";
export {
    FunctionContract,
    FunctionContractBuilder,
    functionBuilder,
    functionBuilder as function,
    type FunctionContractOptions,
    type FunctionInputShape,
    type FunctionOutput,
    type InferFunctionArgs
} from "./function.js";
export {
    ObjectGuard,
    atLeastOneKey,
    catchall,
    deepPartial,
    exactlyOneKey,
    extend,
    keyofObject,
    loose,
    looseObject,
    merge,
    nonpassthrough,
    nonstrict,
    object,
    oneOfKeys,
    omit,
    partial,
    passthrough,
    pick,
    required,
    safeExtend,
    strict,
    strictObject,
    strip,
    type DeepPartialObjectShape,
    type DeepPartialValue,
    type InferObject,
    type MaskSelectedKeys,
    type MergeObjectShapes,
    type ObjectKeyMask,
    type ObjectGuardMode,
    type ObjectShape,
    type OmitObjectShape,
    type OmitObjectShapeByMask,
    type PartialObjectShape,
    type PartialObjectShapeByMask,
    type PickObjectShape,
    type PickObjectShapeByMask,
    type RequiredObjectShape,
    type RequiredObjectShapeByMask
} from "./object/index.js";
export {
    bigintGuard,
    booleanGuard,
    base64,
    base64url,
    cidrv4,
    cidrv6,
    cuid,
    cuid2,
    dateGuard,
    e164,
    email,
    emoji,
    enumValues,
    enumValues as enum,
    file,
    float32,
    float64,
    guid,
    hash,
    hex,
    hostname,
    httpUrl,
    ipv4,
    ipv6,
    iso,
    isoDate,
    isoDateTime,
    isoDuration,
    isoTime,
    jwt,
    int,
    int32,
    int64,
    literal,
    ksuid,
    mac,
    nan,
    nanoid,
    neverGuard,
    nullGuard,
    numberGuard,
    stringFormat,
    symbolGuard,
    stringGuard,
    unknownGuard,
    uint32,
    uint64,
    ulid,
    url,
    uuid,
    uuidv4,
    uuidv6,
    uuidv7,
    xid,
    undefinedGuard,
    voidGuard,
    type EnumLikeInput,
    type EnumLikeValue,
    type EnumValues,
    type IsoNamespace,
    type LiteralValues,
    type StringEmailOptions,
    type StringIsoDateTimeOptions,
    type StringIsoTimeOptions,
    type StringJwtOptions,
    type StringMacDelimiter,
    type StringMacOptions,
    type StringUrlOptions,
    type StringUuidOptions,
    type StringUuidVersion
} from "./scalar.js";
export {
    instanceOf,
    json,
    property,
    type InstanceConstructor,
    type JsonValue
} from "./runtime.js";
export { t, z } from "./table.js";
export type {
    InferTuple,
    InferTupleWithRest,
    TupleShape
} from "./types.js";
